### ISSUE TITLE
Changes to the looks and text

### ISSUE THREAD

**Issue by klesun** [dogzy123/klesun-productions#1]
- ~~Return the "Programming odd jobs" header~~
- ~~Return "Taking orders of any scale on any technology" to follow the "A "write a program for me" service" part.~~
- ~~Make sizes as follows: "Programming odd jobs" **big**; "A "write a program for me" service. Taking orders of any scale on any technology" **smaller**; rest - **just the size of normal text**.~~
- ~~Change "plugins for other apps (including browsers)" to just "plugins"~~
- ~~Change "Contact Us" to "Order Software"~~
- ~~Make "The job price is case-to-case matter of discussion, but in general it's around $20 per estimated working hour" aligned to the left, not center. And place it to the same block as "We are writing web apps..." part.~~
- ~~Change "We aim for the max mutual..." to the "Our main selling point is that we aim for the mutual..."~~
- ~~Make "Dirty deeds done dirty cheep" twice smaller, to be in the bottom of the page and aligned to the right.~~
- Add icons to "Our popular projects": ![](https://midiana.lv/imgs/deep_16_ruby2.png) ![](https://midiana.lv/favicon.ico) ![image](https://user-images.githubusercontent.com/5202330/68730416-54f90400-05d5-11ea-8344-949d551d8fed.png) (use `rendering: pixelated` css - for nice scaling without soap)
- Add [riddle-needle](https://github.com/klesun/riddle-needle) to the list with icon: ![](https://raw.githubusercontent.com/klesun/riddle-needle/master/Assets/Images/heroine.png)
- Change "github profile" to just "github" and make it point to the https://github.com/klesun?tab=repositories rather than home page. And move it outside the "Our popular projects" section, since it is not a project, not popular and not ours.

- Would be nice to have a link to the old midiana.lv page somewhere (later will move it to be a subdomain of klesun-productions.com or smth)

**Comment by dogzy123** [comment]
~~~- Return the "Programming odd jobs" header~~~
~~~- Return "Taking orders of any scale on any technology" to follow the "A "write a program for me" service" part.~~~
~~~- Make sizes as follows: "Programming odd jobs" **big**; "A "write a program for me" service. Taking orders of any scale on any technology" **smaller**; rest - **just the size of normal text**.~~~
~~~- Change "plugins for other apps (including browsers)" to just "plugins"~~~
~~~- Change "Contact Us" to "Order Software"~~~
~~~- Make "The job price is case-to-case matter of discussion, but in general it's around $20 per estimated working hour" aligned to the left, not center. And place it to the same block as "We are writing web apps..." part.~~~
~~~- Change "We aim for the max mutual..." to the "Our main selling point is that we aim for the mutual..."~~~
~~~- Make "Dirty deeds done dirty cheep" twice smaller, to be in the bottom of the page and aligned to the right.~~~
- Add icons to "Our popular projects": ![](https://midiana.lv/imgs/deep_16_ruby2.png) ![](https://midiana.lv/favicon.ico) ![image](https://user-images.githubusercontent.com/5202330/68730416-54f90400-05d5-11ea-8344-949d551d8fed.png) (use `rendering: pixelated` css - for nice scaling without soap) 
- Add [riddle-needle](https://github.com/klesun/riddle-needle) to the list with icon: ![](https://raw.githubusercontent.com/klesun/riddle-needle/master/Assets/Images/heroine.png)
**-I don't know if it is a good idea to place an icons in there :/**
~~~- Change "github profile" to just "github" and make it point to the https://github.com/klesun?tab=repositories rather than home page.~~~ And move it outside the "Our popular projects" section, since it is not a project, not popular and not ours.

- Would be nice to have a link to the old midiana.lv page somewhere (later will move it to be a subdomain of klesun-productions.com or smth)

**Comment by brxkensmile** [comment]
~~- Return the "Programming odd jobs" header~~
~~- Return "Taking orders of any scale on any technology" to follow the "A "write a program for me" service" part.~~
~~- Make sizes as follows: "Programming odd jobs" **big**; "A "write a program for me" service. Taking orders of any scale on any technology" **smaller**; rest - **just the size of normal text**.~~
~~- Change "plugins for other apps (including browsers)" to just "plugins"~~
~~- Change "Contact Us" to "Order Software"~~
~~- Make "The job price is case-to-case matter of discussion, but in general it's around $20 per estimated working hour" aligned to the left, not center. And place it to the same block as "We are writing web apps..." part.~~
~~- Change "We aim for the max mutual..." to the "Our main selling point is that we aim for the mutual..."~~
~~- Make "Dirty deeds done dirty cheep" twice smaller, to be in the bottom of the page and aligned to the right.~~
- Add icons to "Our popular projects": ![](https://midiana.lv/imgs/deep_16_ruby2.png) ![](https://midiana.lv/favicon.ico) ![image](https://user-images.githubusercontent.com/5202330/68730416-54f90400-05d5-11ea-8344-949d551d8fed.png) (use `rendering: pixelated` css - for nice scaling without soap) 
- Add [riddle-needle](https://github.com/klesun/riddle-needle) to the list with icon: ![](https://raw.githubusercontent.com/klesun/riddle-needle/master/Assets/Images/heroine.png)
**-I don't know if it is a good idea to place an icons in there :/**
~~- Change "github profile" to just "github" and make it point to the https://github.com/klesun?tab=repositories rather than home page.~~ And move it outside the "Our popular projects" section, since it is not a project, not popular and not ours.

- Would be nice to have a link to the old midiana.lv page somewhere (later will move it to be a subdomain of klesun-productions.com or smth)

**Comment by klesun** [comment]
> -I don't know if it is a good idea to place an icons in there :/

I thought that this list looks kinda boring as it is now. The fact that each of the projects has a distinguishable logo seemed pretty convenient for that matter. What's bad with small icons next to project names?

**Comment by klesun** [comment]
Besides the icons, could you, please, make few more adjustments to the "Our popular projects"
![image](https://user-images.githubusercontent.com/5202330/70618825-6ce79600-1c1c-11ea-8023-3000954f094f.png)

- Make the text look more like links: with more specific color (blue for example), with the hover,  color change if visited and stuff. Cuz now they don't look like they are clickable at all.
- ~~Could you, please, align "src" to the right (so that all "src" were lined together)?~~

**Comment by klesun** [comment]
Also, could you, please, use my dogie as the icon instead of electron logo?
![image](https://user-images.githubusercontent.com/5202330/70619120-00b96200-1c1d-11ea-8fc1-8766f5faf330.png)

<sup>Need more dogies everywhere!</sup>

**Comment by klesun** [comment]
Filed unresolved points in a separate issue - https://github.com/dogzy123/klesun-productions/issues/4
